version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    working_directory: /temp
    docker:
      - image:  mcr.microsoft.com/dotnet/sdk:5.0-focal
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
    steps:
      # Checkout source code and try to build & pack
      - checkout
      - run: dotnet restore PostHog.NET\PostHog.NET.csproj
      - run: dotnet build PostHog.NET\PostHog.NET.csproj --configuration Release
  pack:
    working_directory: /pack
    executor:  
      name: win/default
    steps:
      - checkout
      - run:
          name: Generating Nuget Package
          command: dotnet pack -o /packages -c Release PostHog.NET\PostHog.NET.csproj
      - store_artifacts:
          path: /packages/
  test:
    working_directory: /test
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
    steps:
      - checkout
      - run: dotnet restore Test/Test.csproj
      - run: dotnet test Test/Test.csproj
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - pack:
          requires:
            - build  